version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t casetest:latest .
      - docker tag casetest:latest 593204228656.dkr.ecr.us-east-2.amazonaws.com/thisworks
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 593204228656.dkr.ecr.us-east-2.amazonaws.com/thisworks:latest
